{% set version = "1.0.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biwt
  version: {{ version|replace("-", "_") }}

source:
  fn: biwt_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/biwt_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/biwt/biwt_{{ version }}.tar.gz

  sha256: 9c3528c5a4d2982d992f15086bad6bc8de291fe3c77ab0119b80350e6540e33d

build:
  noarch: generic
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-rrcov

  run:
    - r-base
    - r-mass
    - r-rrcov

test:
  commands:
    - $R -e "library('biwt')"  # [not win]
    - "\"%R%\" -e \"library('biwt')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=biwt
  license: GPL-2.0-only
  summary: Compute multivariate location, scale, and correlation estimates based on Tukey's biweight M-estimator.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
