# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "zyEIxT8/CuBT1yZEJaKnAE/u0RgZ39aqgwowlxrHyaZWbdAg4To1kuL5GPoJJM2nqtZJg/xZqX94ni22+8wt5U3lpelivXr5p/p4hcYdLXwiKom7hxWvwNmBfjuMvdAwo+OD59Gy2httQO9OxWmmIQy+tLKYxiG7xPRqwkoVWl2ERIXb9Gkixr/5lAnFNnYZFp23S0LPyk79EfYKoyMS82F37zT9U/7OffImYNA/Cc3M8euDBla+CZZ9ctUvNKzgXJmSu8MLIKvptqGukbnHt7DtohTI0CyXHDyXxdeYs/ITdDGEr8M6qBc/j7JZmeGmylxIDIoOLCvkDwYg2+dbrO6I9EQYY0c523Z4YGmcnli+g4YU2/aEFyxiwZAKsqybweyDnMXd1ZWFd4LWQUiCOxrFNbECkQGDjHzofih2KImyudyEnUB2/oYuyNUJm8C9LxCicdAEq7BJAEcE7iCLavhBAVpmPhj+ChpLkR9lPXwuxVBEl1JWE6pJvKcdtZZnbu992QnkNecXIiWuFbkUlloW7fqFZyhvTc77EeLH5ihlfh3kh3ZkkVjQmiZm1hCfPUKJtuv4XZ+fC8O5PQ5ST6GL0flOk+YiZK/WwVNRpMSwDiq38nMwtP3Ii9EGqB0V38M0wnLJKXXOB2U5AWy5LzscGzKEX7Wmas5iR7cl3Yc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
