appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: zyEIxT8/CuBT1yZEJaKnAE/u0RgZ39aqgwowlxrHyaZWbdAg4To1kuL5GPoJJM2nqtZJg/xZqX94ni22+8wt5U3lpelivXr5p/p4hcYdLXwiKom7hxWvwNmBfjuMvdAwo+OD59Gy2httQO9OxWmmIQy+tLKYxiG7xPRqwkoVWl2ERIXb9Gkixr/5lAnFNnYZFp23S0LPyk79EfYKoyMS82F37zT9U/7OffImYNA/Cc3M8euDBla+CZZ9ctUvNKzgXJmSu8MLIKvptqGukbnHt7DtohTI0CyXHDyXxdeYs/ITdDGEr8M6qBc/j7JZmeGmylxIDIoOLCvkDwYg2+dbrO6I9EQYY0c523Z4YGmcnli+g4YU2/aEFyxiwZAKsqybweyDnMXd1ZWFd4LWQUiCOxrFNbECkQGDjHzofih2KImyudyEnUB2/oYuyNUJm8C9LxCicdAEq7BJAEcE7iCLavhBAVpmPhj+ChpLkR9lPXwuxVBEl1JWE6pJvKcdtZZnbu992QnkNecXIiWuFbkUlloW7fqFZyhvTc77EeLH5ihlfh3kh3ZkkVjQmiZm1hCfPUKJtuv4XZ+fC8O5PQ5ST6GL0flOk+YiZK/WwVNRpMSwDiq38nMwtP3Ii9EGqB0V38M0wnLJKXXOB2U5AWy5LzscGzKEX7Wmas5iR7cl3Yc=
